import { rollupAdapter, fromRollup } from '@web/dev-server-rollup';
import rollupCommonjs from '@rollup/plugin-commonjs';

const commonjs = fromRollup(rollupCommonjs);

/** @type { import('@web/storybook-framework-web-components').StorybookConfig } */
const config = {
  stories: ["../src/**/*.stories.js"],
  addons: ["@storybook/addon-links", "@storybook/addon-essentials"],
  framework: {
    name: "@web/storybook-framework-web-components",
    options: {},
  },
  docs: {
    autodocs: "tag",
  },
  wdsFinal: (config) => {
    // necessary because autogenerated docs rely on Tocbot which uses commonjs imports
    config.plugins?.unshift(commonjs())
    return config;
  },
  rollupFinal: (config) => {
    config.plugins.unshift(rollupCommonjs())
    return config;
  }
};
export default config;
